server.port=8080
spring.application.name=climalert
spring.threads.virtual.enabled=true

# Integracion con WeatherAPI
weather.api.base-url=http://api.weatherapi.com/v1
weather.api.key=c38c7fa444334bee869122440260607
weather.api.location=Buenos Aires

# Frecuencias de las tareas
scheduler.clima.fixed-rate=300000
scheduler.alertas.fixed-rate=60000

# Alertas
alertas.remitente=${spring.mail.username}
alertas.destinatarios=admin@clima.com,emergencias@clima.com,meteorologia@clima.com

# Correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lmazzini@frba.utn.edu.ar
spring.mail.password=udys xvmb rrun pqwd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.ar.edu.utn.frba.ddsi.climalert=INFO
